version: '3.4'

services:
  db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: lAKB8oJgz8oFSa43ENSY5dMOAxbg1O
      ACCEPT_EULA: "Y"
  grader:
    image: hasanhasanov/grader
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - "ConnectionStrings__GradeR=Data Source=db;Initial Catalog=GradeR;User Id=SA; Password=lAKB8oJgz8oFSa43ENSY5dMOAxbg1O"
      - "Logging__LogLevel__Default=Information"
    ports:
      - "8080:80"
    depends_on: 
      - db